### ISSUE TITLE
Eating while pvping issue

### ISSUE THREAD

**Issue by LaughNgamez** [NoCheatPlus/Issues#318]
#### Short description of the issue.
When a user is being constanly hit while eating a gold apple/possibly other food items it cancels the eating unless fastconsume/instanteat is disabled.

#### Complete output of the _ncp version_ command (please prefer text here).
http://pastebin.com/vYT32juw

#### How to reproduce the issue (is it random / always happens / side conditions)?
Seems to always happen

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Nothing to do with fastconsume/instanteat. Really only config changes are increasing leniency of other checks.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Compactnocheatplus but only hooking with magicspells

**Comment by asofold** [comment]
Looks like the ncp version output is cut off - e.g. the version of NoCheatPlus itself is missing :), as well as MCAccess and MC version detection...

Possibly related:
* Latest builds contain a fix concernbing force disabling instanteat not done on 'ncp reload'. 

If the astconsume check is available, instanteat must be disabled, otherwise it'll interfere. So the suggestion is to check if instanteat ever was involved, and if so, update to the latest appropriate development build (fixed in build 1037, for 1.10 better have 1039/later).

The version of CompatNoCheatPlus (b83) will not be compatible with the latest builds of NCP, latest versions of cncp are at http://ci.md-5.net/job/CompatNoCheatPlus/ , however MagicSpells support has been removed there ( - it might be that the MagicSpells developer has already added some level of compatibility on their own! ~ Needs evaluation).

**Comment by 0XE4** [comment]
This is happening on 1038 just FYI

**Comment by asofold** [comment]
@0XE4 But there should be no "instanteat" violations then... are there any? Do you have any violation logs (preferably with [tags] in the messages)?

Debug logs of the issue typically speed up things significantly, of course...

**Comment by MarkElf** [comment]
A similar issue occurs with enderpearls so the issue is tied with damage canceling the consuming event. Modifying the duration between 0.6 to 0.8 for fast consume does not resolve the issue. I had someone provide the video below. 

https://www.youtube.com/watch?v=VSmbB5hKR10

**Comment by asofold** [comment]
Assuming the 'instanteat not disabling' being resaolved on latest builds, it appears odd to see this. Data should only reset with...
* Consuming something (ItemConsumeEvent)
* Interacting with blocks (PlayerInteractEvent)
* Changing the item (PlayerItemHeldEvent)
* (Data removal)

Unless i am mistaken, any of these have to fire, in order to invalidate anything.

Which MC versions is this about? I'm still lacking this input. I'll try to reproduce on 1.11 with ender pearls then.

**Comment by asofold** [comment]
@MarkElf Can't reproduce on 1.11 with ender pearls (not tried extensively, but some), Any hints on how to do rerpoduce this using ender pearls?

Otherwise are any other side conditions known? 
* Protocol support plugins.
* MC versions (...)
* Other plugins doing something with NCP / damage ? Skills that alter knockback ?

**Comment by LaughNgamez** [comment]
I've tried running two versions of NCP. Currently running Spigot for 1.10. Have a plugin which alters player hit speed when holding items but it should not affect the testing as it does not alter fist hit speed.

I'll run a test ASAP with no other plugins.

**Comment by asofold** [comment]
If you hit the ground (interaction) while eating, the timing will reset.

This is what i forgot to ask...
* Hitting while right clicking the item at the same time? (Not relevant if others hit you for that scenario ... )

**Comment by LaughNgamez** [comment]
Well you hold down right click to eat so perhaps that explains it?

**Comment by asofold** [comment]
@LaughNgamez What i meant was hold right click while left click to hit others?

**Comment by LaughNgamez** [comment]
Ah will look into that, also to answer an earlier question users have been getting a fast consume violation level.

**Comment by LaughNgamez** [comment]
@asofold So just to be clear you want me to hold right click while hitting someone who is eating an apple?

**Comment by asofold** [comment]
@LaughNgamez Sorry, no :), good you're asking back. I have to clarify:

Concerning the player who eats and causes fastconsume violations:
* What resets the fastconsume data is:
 *  Consuming something (ItemConsumeEvent)
 *  Interacting with blocks (PlayerInteractEvent) - This can happen when the same player tries to hit others as well while eating (despite rather impossible / cheating).
 *  Changing the item (PlayerItemHeldEvent)
 *  (Data removal)

Other players who attack the player who is eating can do:
* Kill the player (...).
* (Nothing really.)

So forget about the 'eating while hitting' part, i have tried that on 1.11 (you eat + you hit blocks).

We'll just need more information - build 1040 contains increased debug logging for fastconsume (but it also contains some other internal changes, so take a little care with production servers). This demands creating debug logs of a player who tries to eat and who triggers fastconsume (...). If that is not possible, we'll need more information about plugins in use (any with interaction, item managment server side and client side?, skills that alter stuff on eating (more hunger/health for certain items like mcMMO), plugins "optimize" NCP itself), and if possible also more about side conditions (how often, can it be confined to certain  circumstances...

**Comment by v0idst4r** [comment]
This also occurs when just taking fire damage, super annoying when trying to regenerate health...

**Comment by asofold** [comment]
isntanteat enabling 'randomly' should be long fixed, asusme fixed at least in build 1084-RC - please note here or in a new issue, if issues persist.
