### ISSUE TITLE
"[check]" variable doesn't get parsed in "cmd:" actions

### ISSUE THREAD

**Issue by Maxetto** [NoCheatPlus/Issues#390]
#### Short description of the issue.
Pretty self explainatory, I would like to generalize the ban command with "ban [player] Cheat: [check]" but the "[check]" variable doesn't get parsed, so the output would be "ban Maxetto Cheat: [check]".

#### Complete output of the _ncp version_ command (please prefer text here).
```
---- Version information ----
#### Server ####
git-PaperSpigot-"4c7641d" ~MC: 1.8.8~
detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1064
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v3.6.5
```

**Comment by MarkElf** [comment]
I would try adding "ncp delay" in front of the ban command that you originally had to ensure ncp is running the command, not just the banning plugin. I haven't tried it myself as I'm not by a computer at the moment, but I'm sure you'll have a chance to test it if anything.

**Comment by asofold** [comment]
In general NCP should replace placeholders just like with log actions. E.g. if [player] works but [check] not it would indicate a bug.

@Maxetto Could you show the strings part of the command action? Is any part getting replaced or none?

(@MarkElf  Does 'ncp delay' improve things here ?! )

**Comment by Maxetto** [comment]
Sure thing:
```
actions: cancel vl>10 log:bautosign:0:6:i cancel vl>30 cmd:cccheatban:0:2 cancel log:banmessage:0:5:ci vl>45 cmd:cheatban1:0:2 cancel log:banmessage:0:5:ci vl>55 cmd:ccheatban:0:2 cancel log:banmessage:0:5:ci
```

Where their relative commands are:
```
cccheatban: 'cc [player] unless -ping->81|-tps-<19.5 do tempban [player] 7d [NCP] Cheat: [check]'
ccheatban: 'tempban [player] 7d [NCP] Cheat: [check]'
cheatban: 'cc [player] unless -ping->151|-tps-<19.2 do tempban [player] 7d [NCP] Cheat: [check]'
```

**Comment by MarkElf** [comment]
@asofold I thought I'd mention it in the event that ncp has the command run directly through console rather than being ran through ncp running it through an alternative method. I could be wrong on that, but wanted to include it as a possible solution; obviously you know how your plugin works better than I ever could. If I am wrong, feel free to simply disregard my comment.

**Comment by asofold** [comment]
@MarkElf The idea isn't far off, but NCP should do all replacing before  running _any_ command. 

@Maxetto Thinking about it, is there some error line in the log at startup or randomly later, that NCP can't interpret 'NCP' ? I.e. If only the messages with [NCP] in them fail, could you try those without the [NCP] parts?

**Comment by Maxetto** [comment]
No, nothing in the logs about [NCP].

**Comment by asofold** [comment]
Why has this been marked as 'fixed'? Has this been fixed !?

**Comment by Maxetto** [comment]
Uhm, I don't know. I didn't even know it was set to "fixed". 😛 

I'll try ASAP.

**Comment by MarkElf** [comment]
I believe that was fixed - at least with cmdc it is.

**Comment by Maxetto** [comment]
Fix confirmed.

**Comment by asofold** [comment]
Thanks :).

**Comment by CaptainObvious0** [comment]
Hey, I know this is a closed issue but I would like to add onto this. 

I've found the reason why it was not working in the first place. The reason is the prefix [NCP]. Since it has the brackets [ ], it will not work. If you were to remove the brackets, it will work. The problems still exists if you try to run anything with that. Having any sort of brackets inside that part will make the other variables not work.

**Comment by asofold** [comment]
oopsies - should probably add a translation table in the configuration, so such parts don't get changed.
